# Generated by Django 3.1.6 on 2021-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210404_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='notes',
        ),
        migrations.AddField(
            model_name='spot',
            name='geojson',
            field=models.TextField(default='foo'),
            preserve_default=False,
        ),
    ]
